version: '3'

services:
    db:
        image: postgis/postgis
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=postgres
        ports:
            - "5432:5432"
    migration:
        build: .
        command: python manage.py migrate --noinput
        volumes:
            - .:/app
        depends_on:
            - db

    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/app
        ports:
        - "8000:8000"
        depends_on:
            - db

