# Generated by Django 5.0.4 on 2024-05-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='external_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
